/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Election } from "./Election";
import { ElectionCountArgs } from "./ElectionCountArgs";
import { ElectionFindManyArgs } from "./ElectionFindManyArgs";
import { ElectionFindUniqueArgs } from "./ElectionFindUniqueArgs";
import { CreateElectionArgs } from "./CreateElectionArgs";
import { UpdateElectionArgs } from "./UpdateElectionArgs";
import { DeleteElectionArgs } from "./DeleteElectionArgs";
import { VoteFindManyArgs } from "../../vote/base/VoteFindManyArgs";
import { Vote } from "../../vote/base/Vote";
import { ElectionService } from "../election.service";
@graphql.Resolver(() => Election)
export class ElectionResolverBase {
  constructor(protected readonly service: ElectionService) {}

  async _electionsMeta(
    @graphql.Args() args: ElectionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Election])
  async elections(
    @graphql.Args() args: ElectionFindManyArgs
  ): Promise<Election[]> {
    return this.service.elections(args);
  }

  @graphql.Query(() => Election, { nullable: true })
  async election(
    @graphql.Args() args: ElectionFindUniqueArgs
  ): Promise<Election | null> {
    const result = await this.service.election(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Election)
  async createElection(
    @graphql.Args() args: CreateElectionArgs
  ): Promise<Election> {
    return await this.service.createElection({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Election)
  async updateElection(
    @graphql.Args() args: UpdateElectionArgs
  ): Promise<Election | null> {
    try {
      return await this.service.updateElection({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Election)
  async deleteElection(
    @graphql.Args() args: DeleteElectionArgs
  ): Promise<Election | null> {
    try {
      return await this.service.deleteElection(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Vote], { name: "votes" })
  async findVotes(
    @graphql.Parent() parent: Election,
    @graphql.Args() args: VoteFindManyArgs
  ): Promise<Vote[]> {
    const results = await this.service.findVotes(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
